version: "3.8"
services:
    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: ping-pong
        networks:
            - postgres
    pgadmin:
        links:
            - postgres:postgres
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "8080:80"
        volumes:
            - /data/pgadmin:/root/.pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        networks:
            - postgres
    api:
        build:
            context: ./
        volumes:
            - .:/src
        command: npm run start
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        networks:
            - postgres

    postgres-test:
        image: postgres:10.4
        ports:
            - "35001:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: ping-pong
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
